# Gradle Args
org.gradle.jvmargs=-Xmx4G

org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=false
org.gradle.caching=true

# Mod Properties
archives_base_name=Estrogen
version=4.3.2+1.20.1
group=dev.mayaqq
modid=estrogen

# Enables
devauth_enabled=true

# Item Viewer
# JEI or disabled
item_viewer_forge=disabled
# EMI, JEI, REI or disabled
item_viewer_fabric=disabled

# Mod Info
contributors=PrincessDoreena (dev), TheWinABagel (arch port contributor), rosymaplemoss (Liquid Estrogen Texture & Moth Model), erora (Music), Falkory (New Textures), Naomi (Jar), Sery (Dream Block Texture), m0ft (Moth Animations), ThatGravyBoat (Ton of fixes and changes)
