# Gradle Args // The memory is higher because when building both forge and fabric, it sometimes runs out
org.gradle.jvmargs=-Xmx4G

org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=false
org.gradle.caching=true

# Mod Properties
archives_base_name=Estrogen
mod_version=4.3.2+1.20.1
maven_group=dev.mayaqq
modid=estrogen

# Common Dependencies
parchment_version=2023.09.03
architectury_version=9.1.12
fabric_version=0.16.9
devauth_version=1.2.1
create_fabric_version=0.5.1-f-build.1224
trinkets_version=3.7.1
rei_version=12.0.626
emi_version=1.0.29
jei_version=15.2.0.27
mixin_extras_version=0.3.5
jukeboxfix_version=1.0.1
ears_version=1.4.5
figura_version=0.1.4
baubly_version=1.0.1
resourcefullib_version=2.1.29
botarium_version=2.3.3
new_age_version=1.1.2
resourceful_cosmetics_version=1.0.4
critter_version=0.1-beta.14
skinlayers_version=5edNc5ga
cobblemon_version=1.5.2
mixin_version=0.8.3

# Fabric Only Dependencies
fapi_version=0.92.2
modmenu_version=7.2.2
cardinal_version=5.2.2
jei_file_id_fabric=5101365
flk_version=1.11.0+kotlin.2.0.0

# Forge Only Dependencies
forge_version=47.2.19
curios_version=5.4.7
create_forge_version=0.5.1.f-27
flywheel_version=0.6.10-7
jei_file_id_forge=4712868
kff_version=4.11.0

# Enables
devauth_enabled=true
skinlayer_enabled=true

# Waygl
waygl_version=3CHQaaxS
fabric_language_kotlin_version=1.12.3+kotlin.2.0.21
yacl_version=3.6.1+1.20.1-fabric

# Item Viewer
# JEI or disabled
item_viewer_forge=JEI
# EMI, JEI, REI or disabled
item_viewer_fabric=EMI

# Cardinal Components Configuration
cardinal_modules=base, entity

# Mod Info
contributors=PrincessDoreena (dev), TheWinABagel (arch port contributor), rosymaplemoss (Liquid Estrogen Texture & Moth Model), erora (Music), Falkory (New Textures), Naomi (Jar), Sery (Dream Block Texture), m0ft (Moth Animations), ThatGravyBoat (Ton of fixes and changes)
