# Gradle Args
org.gradle.jvmargs=-Xmx4G

org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.caching=true
earth.terrarium.cloche.disable-class-extensions=true

# Mod Properties
archives_base_name=Estrogen
version=6.0.0+1.21.1-alpha.4
group=dev.mayaqq
modid=estrogen
mod_name=Estrogen

maven_category=nightly
use_maven_local=true

# Enables
devauth_enabled=true

# EMI, JEI, REI or disabled
item_viewer=EMI