[versions]

# Stuff
kotlin = "2.4.0"
cloche = "0.19.13"

# Minecraft
minecraft = "1.21.1"
fabric = "0.18.5"

# Common Dependencies
kritter = "2.0.0-alpha.54"
kotlinx-serialization = "1.8.0"
kotlinx-coroutines = "1.10.1"
parchment = "2024.11.17"
devauth = "1.2.1"
trinkets = "3.10.0"
rei = "16.0.799"
emi = "1.1.24+1.21.1"
mixin_extras = "0.5.3"
ears = "1.4.5"
figura = "0.1.4+1.20.1"
csr = "0.0.9"
new_age = "1.1.2"
resourceful_cosmetics = "1.0.5"
cobblemon = "1.5.2+1.20.1"
mixin = "0.8.3"
iris = "1.7.6+1.20.1"
flywheel = "1.0.6"
cynosure = "1.0.0.39"
rlib = "3.0.12"
lattice = "1.4.0"

# Fabric Only Dependencies
fapi = "0.116.12"
modmenu = "11.0.4"
cardinal = "6.1.3"
je-fabric = "19.27.0.343-fabric"
flk = "1.13.12+kotlin.2.4.0"

# Neoforge Only Dependencies
neoforge = "21.1.233"
jei-forge = "19.27.0.343-neoforge"
kff = "5.12.0"
curios = "9.5.1+1.21.1"

# Extra Dependencies


[libraries]

# Common Dependencies
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
ears = { module = "com.unascribed:ears-api", version.ref = "ears" }
figura = { module = "org.figuramc:figura-common-mojmap", version.ref = "figura" }
createNewAge = { module = "maven.modrinth:create-new-age", version.ref = "new_age" }
mixinExtras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin_extras" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
flywheel-api = { module = "dev.engine-room.flywheel:flywheel-common-mojmap-api-1.21.1", version.ref = "flywheel" }
cynosure = { module = "dev.mayaqq.cynosure:cynosure", version.ref = "cynosure" }
cosmetics = { module = "com.teamresourceful:resourceful-cosmetics-4j", version.ref = "resourceful_cosmetics" }
lattice = { module = "com.moulberry:lattice", version.ref = "lattice" }

# Fabric dependencies
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "flk" }
fabric-trinkets = { module = "dev.emi:trinkets", version.ref = "trinkets" }
fabric-emi = { module = "dev.emi:emi-fabric", version.ref = "emi" }
fabric-rei = { module = "me.shedaniel:RoughlyEnoughItems-fabric", version.ref = "rei" }
fabric-jei = { module = "maven.modrinth:jei", version.ref = "je-fabric" }
fabric-modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
fabric-cardinalComponents-base = { group = "dev.onyxstudios.cardinal-components-api", name = "cardinal-components-base", version.ref = "cardinal" }
fabric-cardinalComponents-entity = { group = "dev.onyxstudios.cardinal-components-api", name = "cardinal-components-entity", version.ref = "cardinal" }
fabric-iris = { module = "maven.modrinth:iris", version.ref = "iris" }
fabric-devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
fabric-kritter = { module = "invoke.kitty.kritter:kritter-1.21.1-fabric", version.ref = "kritter" }
fabric-flywheel-api = { module = "dev.engine-room.flywheel:flywheel-fabric-api-1.21.1", version.ref = "flywheel" }
fabric-flywheel = { module = "dev.engine-room.flywheel:flywheel-fabric-1.21.1", version.ref = "flywheel" }
fabric-csr = { module = "earth.terrarium.common_storage_lib:common-storage-lib-fabric-1.21.1", version.ref = "csr" }
fabric-rlib = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21", version.ref = "rlib" }
fabric-sodium = { module = "maven.modrinth:sodium", version = "mc1.20.1-0.5.13-fabric" }
fabric-indium = { module = "maven.modrinth:indium", version = "1.0.36+mc1.20.1" }
fabric-cobblemon = { module = "com.cobblemon:fabric", version.ref = "cobblemon" }


# Neoforge depencencies
forge-kotlin = { module = "thedarkcolour:kotlinforforge", version.ref = "kff" }
forge-emi = { module = "dev.emi:emi-neoforge", version.ref = "emi" }
forge-jei = { module = "maven.modrinth:jei", version.ref = "jei-forge" }
forge-rei = { module = "me.shedaniel:RoughlyEnoughItems-neoforge", version.ref = "rei" }
forge-mixinExtras = { module = "io.github.llamalad7:mixinextras-neoforge", version.ref = "mixin_extras" }
forge-devauth = { module = "me.djtheredstoner:DevAuth-neoforge", version.ref = "devauth" }
forge-kritter = { module = "invoke.kitty.kritter:kritter-1.21.1-neoforge", version.ref = "kritter" }
forge-kritter-lang = { module = "invoke.kitty.kritter:kritter-1.21.1-neoforge-lang", version.ref = "kritter" }
forge-flywheel-api = { module = "dev.engine-room.flywheel:flywheel-neoforge-api-1.21.1", version.ref = "flywheel" }
forge-flywheel = { module = "dev.engine-room.flywheel:flywheel-neoforge-1.21.1", version.ref = "flywheel" }
forge-csr = { module = "earth.terrarium.common_storage_lib:common-storage-lib-neoforge-1.21.1", version.ref = "csr" }
forge-rlib = { module = "com.teamresourceful.resourcefullib:resourcefullib-neoforge-1.21", version.ref = "rlib" }
forge-curios = { module = "top.theillusivec4.curios:curios-neoforge", version.ref = "curios" }
forge-oculus = { module = "maven.modrinth:oculus", version = "1.20.1-1.8.0" }

# Extra dependencies
nullbus = { module = "uwu.serenity:nullbus", version = "1.7.4" }
tca = { module = "net.minecrell:terminalconsoleappender", version = "1.3.0" }
jcpp = { module = "org.anarres:jcpp", version = "1.4.14" }
glsltransformer = { module = "io.github.douira:glsl-transformer", version = "2.0.1" }

[bundles]
fabric-cardinalComponents = [
    "fabric-cardinalComponents-base",
    "fabric-cardinalComponents-entity",
]

[plugins]
cloche = { id = "earth.terrarium.cloche", version.ref = "cloche" }
modpublish = { id = "me.modmuss50.mod-publish-plugin", version = "1.1.0" }
