[versions]

# Stuff
kotlin = "2.2.10"
cloche = "0.18.14"

# Minecraft
minecraft-1201 = "1.20.1"
minecraft-1211 = "1.21.1"
fabric = "0.16.9"

# Common Dependencies
kritter = "2.0.0-alpha.4"
kotlinx-serialization="1.8.0"
kotlinx-coroutines="1.10.1"
parchment-1201 = "2023.09.03"
parchment-1211 = "2024.11.17"
devauth = "1.2.1"
trinkets-1201 = "3.7.1"
trinkets-1211 = "3.10.0"
rei-1201 = "12.1.785"
rei-1211 = "16.0.799"
emi-1201 = "1.1.24+1.20.1"
emi-1211 = "1.1.24+1.20.1"
mixin_extras = "0.5.0"
ears = "1.4.5"
figura = "0.1.4+1.20.1"
botarium = "2.3.4" # FUCK FUCK FUCK
new_age = "1.1.2"
resourceful_cosmetics = "1.0.5"
cobblemon = "1.5.2+1.20.1"
mixin = "0.8.3"
iris = "1.7.6+1.20.1"
flywheel = "1.0.2"
cynosure = "1.0.0-local.7"

# Fabric Only Dependencies
fapi-1201 = "0.92.9"
fapi-1211 = "0.116.12"
modmenu-1201 = "7.2.2"
modmenu-1211 = "11.0.4"
cardinal-1201 = "5.2.3"
cardinal-1211 = "6.1.3"
flk = "1.11.0+kotlin.2.0.0"
jei-fabric-1201 = "15.20.0.132-fabric"
jei-fabric-1211 = "19.27.0.343-fabric"

# Forge Only Dependencies
forge = "47.4.0"
kff-1201 = "4.12.0"
jei-forge-1201 = "15.20.0.132-forge"

# Neoforge Only Dependencies
neoforge = "21.1.233"
kff-1211 = "5.11.0"
jei-neoforge-1211 = "19.27.0.343-neoforge"

[libraries]

# Common Dependencies
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
ears = { module = "com.unascribed:ears-api", version.ref="ears" }
figura = { module = "org.figuramc:figura-common-mojmap", version.ref="figura"}
createNewAge = { module = "maven.modrinth:create-new-age", version.ref = "new_age" }
mixinExtras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin_extras" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
flywheel-api-1201 = { module = "dev.engine-room.flywheel:flywheel-common-mojmap-api-1.20.1", version.ref = "flywheel" }
flywheel-api-1211 = { module = "dev.engine-room.flywheel:flywheel-common-mojmap-api-1.21.1", version.ref = "flywheel" }
cynosure = { module = "dev.mayaqq.cynosure:cynosure", version.ref = "cynosure" }
cosmetics = { module = "com.teamresourceful:resourceful-cosmetics-4j", version.ref = "resourceful_cosmetics" }

# Fabric dependencies
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "flk" }
fabric-trinkets-1201 = { module = "dev.emi:trinkets", version.ref = "trinkets-1201" }
fabric-trinkets-1211 = { module = "dev.emi:trinkets", version.ref = "trinkets-1211" }
fabric-emi-1201 = { module = "dev.emi:emi-fabric", version.ref = "emi-1201" }
fabric-emi-1211 = { module = "dev.emi:emi-fabric", version.ref = "emi-1211" }
fabric-rei-1201 = { module = "me.shedaniel:RoughlyEnoughItems-fabric", version.ref = "rei-1201" }
fabric-rei-1211 = { module = "me.shedaniel:RoughlyEnoughItems-fabric", version.ref = "rei-1211" }
fabric-jei-1201 = { module = "maven.modrinth:jei", version.ref = "jei-fabric-1201" }
fabric-jei-1211 = { module = "maven.modrinth:jei", version.ref = "jei-fabric-1211" }
fabric-modmenu-1201 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-1201" }
fabric-modmenu-1211 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-1211" }
fabric-cardinalComponents-base-1201 = { group = "dev.onyxstudios.cardinal-components-api", name = "cardinal-components-base", version.ref = "cardinal-1201" }
fabric-cardinalComponents-entity-1201 = { group = "dev.onyxstudios.cardinal-components-api", name = "cardinal-components-entity", version.ref = "cardinal-1201" }
fabric-cardinalComponents-base-1211 = { group = "dev.onyxstudios.cardinal-components-api", name = "cardinal-components-base", version.ref = "cardinal-1211" }
fabric-cardinalComponents-entity-1211 = { group = "dev.onyxstudios.cardinal-components-api", name = "cardinal-components-entity", version.ref = "cardinal-1211" }
fabric-iris = { module = "maven.modrinth:iris", version.ref="iris" }
fabric-devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
fabric-flywheel-api-1201 = { module = "dev.engine-room.flywheel:flywheel-fabric-api-1.20.1", version.ref = "flywheel" }
fabric-flywheel-api-1211 = { module = "dev.engine-room.flywheel:flywheel-fabric-api-1.21.1", version.ref = "flywheel" }
fabric-flywheel-1201 = { module = "dev.engine-room.flywheel:flywheel-fabric-1.20.1", version.ref = "flywheel" }
fabric-flywheel-1211 = { module = "dev.engine-room.flywheel:flywheel-fabric-1.21.1", version.ref = "flywheel" }
fabric-kritter-1201 = { module = "invoke.kitty.kritter:kritter-1.20.1-fabric", version.ref = "kritter" }
fabric-kritter-1211 = { module = "invoke.kitty.kritter:kritter-1.21.1-fabric", version.ref = "kritter" }
fabric-sodium = { module = "maven.modrinth:sodium", version = "mc1.20.1-0.5.13-fabric" }
fabric-indium = { module = "maven.modrinth:indium", version = "1.0.36+mc1.20.1" }
fabric-cobblemon = { module = "com.cobblemon:fabric", version.ref = "cobblemon" }

# Forge depencencies
#forge-kotlin = { module = "dev.nyon:KotlinLangForge", version.ref = "klf" }
forge-kotlin-1201 = { module = "thedarkcolour:kotlinforforge", version.ref = "kff-1201" }
forge-kotlin-1211 = { module = "thedarkcolour:kotlinforforge", version.ref = "kff-1211" }
forge-emi-1201 = { module = "dev.emi:emi-forge", version.ref = "emi-1201" }
forge-emi-1211 = { module = "dev.emi:emi-forge", version.ref = "emi-1211" }
forge-jei-1201 = { module = "maven.modrinth:jei", version.ref = "jei-forge-1201" }
forge-jei-1211 = { module = "maven.modrinth:jei", version.ref = "jei-neoforge-1211" }
forge-rei-1201 = { module = "me.shedaniel:RoughlyEnoughItems-forge", version.ref = "rei-1201" }
forge-rei-1211 = { module = "me.shedaniel:RoughlyEnoughItems-neoforge", version.ref = "rei-1211" }
forge-mixinExtras = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixin_extras" }
forge-devauth = { module = "me.djtheredstoner:DevAuth-forge-latest", version.ref = "devauth" }
forge-flywheel-api-1201 = { module = "dev.engine-room.flywheel:flywheel-forge-api-1.20.1", version.ref = "flywheel" }
forge-flywheel-api-1211 = { module = "dev.engine-room.flywheel:flywheel-neoforge-api-1.21.1", version.ref = "flywheel" }
forge-flywheel-1201 = { module = "dev.engine-room.flywheel:flywheel-forge-1.20.1", version.ref = "flywheel" }
forge-flywheel-1211 = { module = "dev.engine-room.flywheel:flywheel-neoforge-1.21.1", version.ref = "flywheel" }
# forge-cynosure = { module = "dev.mayaqq.cynosure:cynosure-forge", version.ref = "cynosure" }
forge-oculus = { module = "maven.modrinth:oculus", version = "1.20.1-1.8.0" }
forge-kritter-1201 = { module = "invoke.kitty.kritter:kritter-1.20.1-forge", version.ref = "kritter" }
forge-kritter-1211 = { module = "invoke.kitty.kritter:kritter-1.21.1-neoforge", version.ref = "kritter" }

[bundles]
fabric-cardinalComponents-1201 = [ "fabric-cardinalComponents-base-1201", "fabric-cardinalComponents-entity-1201" ]
fabric-cardinalComponents-1211 = [ "fabric-cardinalComponents-base-1211", "fabric-cardinalComponents-entity-1211" ]

[plugins]
cloche = { id = "earth.terrarium.cloche", version.ref = "cloche" }
modpublish = { id = "me.modmuss50.mod-publish-plugin", version = "1.1.0" }