package dev.mayaqq.estrogen.neoforge.mixins;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * Nullbus 1.7.4 observes transformed nested event classes with a dotted binary
 * name and turns that dot into a package separator. The JVM descriptor retains
 * the real '$' nested-class separator and is safe to use for generated bytecode.
 */
@Mixin(targets = "uwu.serenity.nullbus.dispatch.internal.ConstantsKt", remap = false)
public abstract class NullbusConstantsMixin {
    @Inject(method = "getInternalName", at = @At("HEAD"), cancellable = true)
    private static void estrogen$useJvmDescriptor(
        Class<?> type,
        CallbackInfoReturnable<String> callback
    ) {
        String descriptor = type.descriptorString();
        if (descriptor.startsWith("L") && descriptor.endsWith(";")) {
            callback.setReturnValue(descriptor.substring(1, descriptor.length() - 1));
        }
    }
}
